### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by alexstewartja** [amiranagram/inertia-codeigniter-4#1]
Is this repository still being worked on or maintained?

**Comment by amiranagram** [comment]
Yes it is, current release is working fine. I just wanted to write some tests before I do a proper release, I just can't seem to find time.

**Comment by alexstewartja** [comment]
Hey, that's what contributors are for bro. Update the README with a Roadmap of features you intend to add and I'll get started on helping you implement them.

**Comment by amiranagram** [comment]
I added a roadmap for starter. Those are the essential tests I wanna cover first. Check out [Inertia Laravel](https://github.com/inertiajs/inertia-laravel/blob/master/tests) for reference.

Thanks a lot for showing interest. Feature-wise there a couple I can think of right now, I'll update the README in the following days.

Feel free to PR anytime.
